/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'Study' : null } |
  { 'Health' : null } |
  { 'Work' : null } |
  { 'Personal' : null } |
  { 'Finance' : null };
export interface CreateTaskInput {
  'title' : string,
  'description' : string,
  'deadline' : [] | [Timestamp],
  'category' : Category,
  'priority' : Priority,
}
export interface DayStats { 'date' : string, 'completedCount' : bigint }
export type Priority = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export interface ProductivityStats {
  'totalTasks' : bigint,
  'completionRate' : bigint,
  'completedTasks' : bigint,
  'monthlyCompleted' : bigint,
  'weeklyChart' : WeeklyChart,
  'pendingTasks' : bigint,
}
export interface Task {
  'id' : TaskId,
  'title' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'completed' : boolean,
  'description' : string,
  'deadline' : [] | [Timestamp],
  'updatedAt' : Timestamp,
  'category' : Category,
  'priority' : Priority,
}
export interface TaskFilter {
  'deadlineTo' : [] | [Timestamp],
  'deadlineFrom' : [] | [Timestamp],
  'completed' : [] | [boolean],
  'searchText' : [] | [string],
  'category' : [] | [Category],
  'priority' : [] | [Priority],
}
export type TaskId = bigint;
export type Timestamp = bigint;
export interface UpdateSettingsInput {
  'theme' : [] | [{ 'dark' : null } | { 'light' : null }],
  'notificationsEnabled' : [] | [boolean],
  'displayName' : [] | [string],
}
export interface UpdateTaskInput {
  'title' : [] | [string],
  'completed' : [] | [boolean],
  'description' : [] | [string],
  'deadline' : [] | [[] | [Timestamp]],
  'category' : [] | [Category],
  'priority' : [] | [Priority],
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettings {
  'theme' : { 'dark' : null } |
    { 'light' : null },
  'notificationsEnabled' : boolean,
  'displayName' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
}
export interface WeeklyChart {
  'days' : Array<DayStats>,
  'totalThisWeek' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTask' : ActorMethod<[CreateTaskInput], Task>,
  'deleteTask' : ActorMethod<[bigint], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProductivityStats' : ActorMethod<[], ProductivityStats>,
  'getTask' : ActorMethod<[bigint], [] | [Task]>,
  'getTasks' : ActorMethod<[[] | [TaskFilter]], Array<Task>>,
  'getUserSettings' : ActorMethod<[], [] | [UserSettings]>,
  'getWeeklyChart' : ActorMethod<[], WeeklyChart>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'toggleTaskComplete' : ActorMethod<[bigint], [] | [Task]>,
  'updateTask' : ActorMethod<[bigint, UpdateTaskInput], [] | [Task]>,
  'updateUserSettings' : ActorMethod<[UpdateSettingsInput], UserSettings>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];