/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Category = IDL.Variant({
  'Study' : IDL.Null,
  'Health' : IDL.Null,
  'Work' : IDL.Null,
  'Personal' : IDL.Null,
  'Finance' : IDL.Null,
});
export const Priority = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const CreateTaskInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'deadline' : IDL.Opt(Timestamp),
  'category' : Category,
  'priority' : Priority,
});
export const TaskId = IDL.Nat;
export const UserId = IDL.Principal;
export const Task = IDL.Record({
  'id' : TaskId,
  'title' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'deadline' : IDL.Opt(Timestamp),
  'updatedAt' : Timestamp,
  'category' : Category,
  'priority' : Priority,
});
export const DayStats = IDL.Record({
  'date' : IDL.Text,
  'completedCount' : IDL.Nat,
});
export const WeeklyChart = IDL.Record({
  'days' : IDL.Vec(DayStats),
  'totalThisWeek' : IDL.Nat,
});
export const ProductivityStats = IDL.Record({
  'totalTasks' : IDL.Nat,
  'completionRate' : IDL.Nat,
  'completedTasks' : IDL.Nat,
  'monthlyCompleted' : IDL.Nat,
  'weeklyChart' : WeeklyChart,
  'pendingTasks' : IDL.Nat,
});
export const TaskFilter = IDL.Record({
  'deadlineTo' : IDL.Opt(Timestamp),
  'deadlineFrom' : IDL.Opt(Timestamp),
  'completed' : IDL.Opt(IDL.Bool),
  'searchText' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(Category),
  'priority' : IDL.Opt(Priority),
});
export const UserSettings = IDL.Record({
  'theme' : IDL.Variant({ 'dark' : IDL.Null, 'light' : IDL.Null }),
  'notificationsEnabled' : IDL.Bool,
  'displayName' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
});
export const UpdateTaskInput = IDL.Record({
  'title' : IDL.Opt(IDL.Text),
  'completed' : IDL.Opt(IDL.Bool),
  'description' : IDL.Opt(IDL.Text),
  'deadline' : IDL.Opt(IDL.Opt(Timestamp)),
  'category' : IDL.Opt(Category),
  'priority' : IDL.Opt(Priority),
});
export const UpdateSettingsInput = IDL.Record({
  'theme' : IDL.Opt(IDL.Variant({ 'dark' : IDL.Null, 'light' : IDL.Null })),
  'notificationsEnabled' : IDL.Opt(IDL.Bool),
  'displayName' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTask' : IDL.Func([CreateTaskInput], [Task], []),
  'deleteTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProductivityStats' : IDL.Func([], [ProductivityStats], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
  'getTasks' : IDL.Func([IDL.Opt(TaskFilter)], [IDL.Vec(Task)], ['query']),
  'getUserSettings' : IDL.Func([], [IDL.Opt(UserSettings)], ['query']),
  'getWeeklyChart' : IDL.Func([], [WeeklyChart], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'toggleTaskComplete' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], []),
  'updateTask' : IDL.Func([IDL.Nat, UpdateTaskInput], [IDL.Opt(Task)], []),
  'updateUserSettings' : IDL.Func([UpdateSettingsInput], [UserSettings], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Category = IDL.Variant({
    'Study' : IDL.Null,
    'Health' : IDL.Null,
    'Work' : IDL.Null,
    'Personal' : IDL.Null,
    'Finance' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const CreateTaskInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'deadline' : IDL.Opt(Timestamp),
    'category' : Category,
    'priority' : Priority,
  });
  const TaskId = IDL.Nat;
  const UserId = IDL.Principal;
  const Task = IDL.Record({
    'id' : TaskId,
    'title' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'deadline' : IDL.Opt(Timestamp),
    'updatedAt' : Timestamp,
    'category' : Category,
    'priority' : Priority,
  });
  const DayStats = IDL.Record({
    'date' : IDL.Text,
    'completedCount' : IDL.Nat,
  });
  const WeeklyChart = IDL.Record({
    'days' : IDL.Vec(DayStats),
    'totalThisWeek' : IDL.Nat,
  });
  const ProductivityStats = IDL.Record({
    'totalTasks' : IDL.Nat,
    'completionRate' : IDL.Nat,
    'completedTasks' : IDL.Nat,
    'monthlyCompleted' : IDL.Nat,
    'weeklyChart' : WeeklyChart,
    'pendingTasks' : IDL.Nat,
  });
  const TaskFilter = IDL.Record({
    'deadlineTo' : IDL.Opt(Timestamp),
    'deadlineFrom' : IDL.Opt(Timestamp),
    'completed' : IDL.Opt(IDL.Bool),
    'searchText' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(Category),
    'priority' : IDL.Opt(Priority),
  });
  const UserSettings = IDL.Record({
    'theme' : IDL.Variant({ 'dark' : IDL.Null, 'light' : IDL.Null }),
    'notificationsEnabled' : IDL.Bool,
    'displayName' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const UpdateTaskInput = IDL.Record({
    'title' : IDL.Opt(IDL.Text),
    'completed' : IDL.Opt(IDL.Bool),
    'description' : IDL.Opt(IDL.Text),
    'deadline' : IDL.Opt(IDL.Opt(Timestamp)),
    'category' : IDL.Opt(Category),
    'priority' : IDL.Opt(Priority),
  });
  const UpdateSettingsInput = IDL.Record({
    'theme' : IDL.Opt(IDL.Variant({ 'dark' : IDL.Null, 'light' : IDL.Null })),
    'notificationsEnabled' : IDL.Opt(IDL.Bool),
    'displayName' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTask' : IDL.Func([CreateTaskInput], [Task], []),
    'deleteTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProductivityStats' : IDL.Func([], [ProductivityStats], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
    'getTasks' : IDL.Func([IDL.Opt(TaskFilter)], [IDL.Vec(Task)], ['query']),
    'getUserSettings' : IDL.Func([], [IDL.Opt(UserSettings)], ['query']),
    'getWeeklyChart' : IDL.Func([], [WeeklyChart], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'toggleTaskComplete' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], []),
    'updateTask' : IDL.Func([IDL.Nat, UpdateTaskInput], [IDL.Opt(Task)], []),
    'updateUserSettings' : IDL.Func([UpdateSettingsInput], [UserSettings], []),
  });
};

export const init = ({ IDL }) => { return []; };