/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface CreateTaskInput {
    title: string;
    description: string;
    deadline?: Timestamp;
    category: Category;
    priority: Priority;
}
export interface Task {
    id: TaskId;
    title: string;
    userId: UserId;
    createdAt: Timestamp;
    completed: boolean;
    description: string;
    deadline?: Timestamp;
    updatedAt: Timestamp;
    category: Category;
    priority: Priority;
}
export type UserId = Principal;
export interface DayStats {
    date: string;
    completedCount: bigint;
}
export interface UpdateSettingsInput {
    theme?: Variant_dark_light;
    notificationsEnabled?: boolean;
    displayName?: string;
}
export type TaskId = bigint;
export interface UserSettings {
    theme: Variant_dark_light;
    notificationsEnabled: boolean;
    displayName: string;
    userId: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
}
export interface TaskFilter {
    deadlineTo?: Timestamp;
    deadlineFrom?: Timestamp;
    completed?: boolean;
    searchText?: string;
    category?: Category;
    priority?: Priority;
}
export interface UpdateTaskInput {
    title?: string;
    completed?: boolean;
    description?: string;
    deadline?: Timestamp | null;
    category?: Category;
    priority?: Priority;
}
export interface WeeklyChart {
    days: Array<DayStats>;
    totalThisWeek: bigint;
}
export interface ProductivityStats {
    totalTasks: bigint;
    completionRate: bigint;
    completedTasks: bigint;
    monthlyCompleted: bigint;
    weeklyChart: WeeklyChart;
    pendingTasks: bigint;
}
export enum Category {
    Study = "Study",
    Health = "Health",
    Work = "Work",
    Personal = "Personal",
    Finance = "Finance"
}
export enum Priority {
    Low = "Low",
    High = "High",
    Medium = "Medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_dark_light {
    dark = "dark",
    light = "light"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createTask(input: CreateTaskInput): Promise<Task>;
    deleteTask(taskId: bigint): Promise<boolean>;
    getCallerUserRole(): Promise<UserRole>;
    getProductivityStats(): Promise<ProductivityStats>;
    getTask(taskId: bigint): Promise<Task | null>;
    getTasks(filter: TaskFilter | null): Promise<Array<Task>>;
    getUserSettings(): Promise<UserSettings | null>;
    getWeeklyChart(): Promise<WeeklyChart>;
    isCallerAdmin(): Promise<boolean>;
    toggleTaskComplete(taskId: bigint): Promise<Task | null>;
    updateTask(taskId: bigint, input: UpdateTaskInput): Promise<Task | null>;
    updateUserSettings(input: UpdateSettingsInput): Promise<UserSettings>;
}
import type { Category as _Category, CreateTaskInput as _CreateTaskInput, Priority as _Priority, Task as _Task, TaskFilter as _TaskFilter, TaskId as _TaskId, Timestamp as _Timestamp, UpdateSettingsInput as _UpdateSettingsInput, UpdateTaskInput as _UpdateTaskInput, UserId as _UserId, UserRole as _UserRole, UserSettings as _UserSettings } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTask(arg0: CreateTaskInput): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(to_candid_CreateTaskInput_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Task_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(to_candid_CreateTaskInput_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Task_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteTask(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductivityStats(): Promise<ProductivityStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductivityStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductivityStats();
            return result;
        }
    }
    async getTask(arg0: bigint): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasks(arg0: TaskFilter | null): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks(to_candid_opt_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks(to_candid_opt_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSettings(): Promise<UserSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSettings();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSettings();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklyChart(): Promise<WeeklyChart> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyChart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyChart();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async toggleTaskComplete(arg0: bigint): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTaskComplete(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTaskComplete(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTask(arg0: bigint, arg1: UpdateTaskInput): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, to_candid_UpdateTaskInput_n27(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, to_candid_UpdateTaskInput_n27(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserSettings(arg0: UpdateSettingsInput): Promise<UserSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserSettings(to_candid_UpdateSettingsInput_n30(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserSettings_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserSettings(to_candid_UpdateSettingsInput_n30(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserSettings_n24(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Category_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserSettings_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserSettings): UserSettings {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Task]): Task | null {
    return value.length === 0 ? null : from_candid_Task_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserSettings]): UserSettings | null {
    return value.length === 0 ? null : from_candid_UserSettings_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TaskId;
    title: string;
    userId: _UserId;
    createdAt: _Timestamp;
    completed: boolean;
    description: string;
    deadline: [] | [_Timestamp];
    updatedAt: _Timestamp;
    category: _Category;
    priority: _Priority;
}): {
    id: TaskId;
    title: string;
    userId: UserId;
    createdAt: Timestamp;
    completed: boolean;
    description: string;
    deadline?: Timestamp;
    updatedAt: Timestamp;
    category: Category;
    priority: Priority;
} {
    return {
        id: value.id,
        title: value.title,
        userId: value.userId,
        createdAt: value.createdAt,
        completed: value.completed,
        description: value.description,
        deadline: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.deadline)),
        updatedAt: value.updatedAt,
        category: from_candid_Category_n12(_uploadFile, _downloadFile, value.category),
        priority: from_candid_Priority_n14(_uploadFile, _downloadFile, value.priority)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: {
        dark: null;
    } | {
        light: null;
    };
    notificationsEnabled: boolean;
    displayName: string;
    userId: _UserId;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
}): {
    theme: Variant_dark_light;
    notificationsEnabled: boolean;
    displayName: string;
    userId: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
} {
    return {
        theme: from_candid_variant_n26(_uploadFile, _downloadFile, value.theme),
        notificationsEnabled: value.notificationsEnabled,
        displayName: value.displayName,
        userId: value.userId,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Study: null;
} | {
    Health: null;
} | {
    Work: null;
} | {
    Personal: null;
} | {
    Finance: null;
}): Category {
    return "Study" in value ? Category.Study : "Health" in value ? Category.Health : "Work" in value ? Category.Work : "Personal" in value ? Category.Personal : "Finance" in value ? Category.Finance : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
}): Priority {
    return "Low" in value ? Priority.Low : "High" in value ? Priority.High : "Medium" in value ? Priority.Medium : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dark: null;
} | {
    light: null;
}): Variant_dark_light {
    return "dark" in value ? Variant_dark_light.dark : "light" in value ? Variant_dark_light.light : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_CreateTaskInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateTaskInput): _CreateTaskInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Priority_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_TaskFilter_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskFilter): _TaskFilter {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateSettingsInput_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateSettingsInput): _UpdateSettingsInput {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateTaskInput_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateTaskInput): _UpdateTaskInput {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskFilter | null): [] | [_TaskFilter] {
    return value === null ? candid_none() : candid_some(to_candid_TaskFilter_n20(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deadlineTo?: Timestamp;
    deadlineFrom?: Timestamp;
    completed?: boolean;
    searchText?: string;
    category?: Category;
    priority?: Priority;
}): {
    deadlineTo: [] | [_Timestamp];
    deadlineFrom: [] | [_Timestamp];
    completed: [] | [boolean];
    searchText: [] | [string];
    category: [] | [_Category];
    priority: [] | [_Priority];
} {
    return {
        deadlineTo: value.deadlineTo ? candid_some(value.deadlineTo) : candid_none(),
        deadlineFrom: value.deadlineFrom ? candid_some(value.deadlineFrom) : candid_none(),
        completed: value.completed ? candid_some(value.completed) : candid_none(),
        searchText: value.searchText ? candid_some(value.searchText) : candid_none(),
        category: value.category ? candid_some(to_candid_Category_n5(_uploadFile, _downloadFile, value.category)) : candid_none(),
        priority: value.priority ? candid_some(to_candid_Priority_n7(_uploadFile, _downloadFile, value.priority)) : candid_none()
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title?: string;
    completed?: boolean;
    description?: string;
    deadline?: Timestamp | null;
    category?: Category;
    priority?: Priority;
}): {
    title: [] | [string];
    completed: [] | [boolean];
    description: [] | [string];
    deadline: [] | [[] | [_Timestamp]];
    category: [] | [_Category];
    priority: [] | [_Priority];
} {
    return {
        title: value.title ? candid_some(value.title) : candid_none(),
        completed: value.completed ? candid_some(value.completed) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        deadline: value.deadline ? candid_some(to_candid_opt_n29(_uploadFile, _downloadFile, value.deadline)) : candid_none(),
        category: value.category ? candid_some(to_candid_Category_n5(_uploadFile, _downloadFile, value.category)) : candid_none(),
        priority: value.priority ? candid_some(to_candid_Priority_n7(_uploadFile, _downloadFile, value.priority)) : candid_none()
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme?: Variant_dark_light;
    notificationsEnabled?: boolean;
    displayName?: string;
}): {
    theme: [] | [{
            dark: null;
        } | {
            light: null;
        }];
    notificationsEnabled: [] | [boolean];
    displayName: [] | [string];
} {
    return {
        theme: value.theme ? candid_some(to_candid_variant_n32(_uploadFile, _downloadFile, value.theme)) : candid_none(),
        notificationsEnabled: value.notificationsEnabled ? candid_some(value.notificationsEnabled) : candid_none(),
        displayName: value.displayName ? candid_some(value.displayName) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    deadline?: Timestamp;
    category: Category;
    priority: Priority;
}): {
    title: string;
    description: string;
    deadline: [] | [_Timestamp];
    category: _Category;
    priority: _Priority;
} {
    return {
        title: value.title,
        description: value.description,
        deadline: value.deadline ? candid_some(value.deadline) : candid_none(),
        category: to_candid_Category_n5(_uploadFile, _downloadFile, value.category),
        priority: to_candid_Priority_n7(_uploadFile, _downloadFile, value.priority)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_dark_light): {
    dark: null;
} | {
    light: null;
} {
    return value == Variant_dark_light.dark ? {
        dark: null
    } : value == Variant_dark_light.light ? {
        light: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    Study: null;
} | {
    Health: null;
} | {
    Work: null;
} | {
    Personal: null;
} | {
    Finance: null;
} {
    return value == Category.Study ? {
        Study: null
    } : value == Category.Health ? {
        Health: null
    } : value == Category.Work ? {
        Work: null
    } : value == Category.Personal ? {
        Personal: null
    } : value == Category.Finance ? {
        Finance: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} {
    return value == Priority.Low ? {
        Low: null
    } : value == Priority.High ? {
        High: null
    } : value == Priority.Medium ? {
        Medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
